spring:
  application:
    name: pickup-provider-family

  cloud:
    config:
      uri: http://localhost:8888
      name: pickup-eureka-client, pickup-client-endpoint
      label: master
      profile: dev

server:
  port: 58083
