spring:
  application:
    name: pickup-zuul
  zipkin:
    base-url: http://localhost:9411
    sleuth:
      sampler:
        percentage: 1.0

server:
  port: 8769

#security:
#  oauth2:
#    client:
#      client-id: ben1
#      client-secret: 123456
#      user-authorization-uri: http://localhost:9000/pickup/oauth/authorize
#      access-token-uri: http://localhost:9000/pickup/oauth/token
#    resource:
#      jwt:
#        key-uri: http://localhost:9000/pickup/oauth/token_key


zuul:
#  prefix: /pickup
  routes:
    pickup-provider-sso:
      path: /sso/**
      serviceId: pickup-provider-sso
    pcikup-provider-parent:
      path: /parent/**
      serviceId: pickup-provider-parent
    pickup-provider-student:
      path: /student/**
      serviceId: pickup=provider-student
