spring:
  application:
    name: pickup-config
  cloud:
    config:
      label: master
      server:
        git:
          uri: https://github.com/9010/PickUp.git
          search-paths: pickup-config/config-repo
          username:
          password:
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      percentage: 1.0

server:
  port: 8888

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,info
