spring:
  application:
    name: pickup-config
  cloud:
    config:
      label: master
      server:
        git:
          uri: https://github.com/9010/PickUp
          search-paths: pickup-config/config-repo
          user: 1106690435@qq.com
          password: ZX199605116016zx
server:
  port: 8888

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,info
